=== FurtherBank/json-schemaeditor-antd/src/schema-example/gen_meta_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$id": "http://json-schema.org/draft-06/schema#",
  "title": "Core schema meta-schema",
  "definitions": {
    "schemaArray": {
      "type": "array",
      "minItems": 1,
      "items": { "$ref": "#/definitions/schema" }
    },
    "nonNegativeInteger": {
      "type": "integer",
      "minimum": 0
    },
    "nonNegativeIntegerDefault0": {
      "allOf": [
        { "$ref": "#/definitions/nonNegativeInteger" },
        { "default": 0 }
      ]
    },
    "simpleTypes": {
      "enum": [
        "array",
        "boolean",
        "integer",
        "null",
        "number",
        "object",
        "string"
      ]
    },
    "stringArray": {
      "type": "array",
      "items": { "type": "string" },
      "uniqueItems": true,
      "default": []
    },
    "schema": {
      "type": "object",
      "properties": {
        "$id": {
          "type": "string",
          "format": "uri-reference"
        },
        "$schema": {
          "type": "string",
          "format": "uri"
        },
        "$ref": {
          "type": "string",
          "format": "uri-reference"
        },
        "title": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "default": {},
        "examples": {
          "type": "array",
          "items": {}
        },
        "multipleOf": {
          "type": "number",
          "exclusiveMinimum": 0
        },
        "maximum": {
          "type": "number"
        },
        "exclusiveMaximum": {
          "type": "number"
        },
        "minimum": {
          "type": "number"
        },
        "exclusiveMinimum": {
          "type": "number"
        },
        "maxLength": { "$ref": "#/definitions/nonNegativeInteger" },
        "minLength": { "$ref": "#/definitions/nonNegativeIntegerDefault0" },
        "pattern": {
          "type": "string",
          "format": "regex"
        },
        "additionalItems": { "$ref": "#/definitions/schema" },
        "items": {
          "anyOf": [{ "$ref": "#/definitions/schema" }, { "$ref": "#/definitions/schemaArray" }],
          "default": {}
        },
        "maxItems": { "$ref": "#/definitions/nonNegativeInteger" },
        "minItems": { "$ref": "#/definitions/nonNegativeIntegerDefault0" },
        "uniqueItems": {
          "type": "boolean",
          "default": false
        },
        "contains": { "$ref": "#/definitions/schema" },
        "maxProperties": { "$ref": "#/definitions/nonNegativeInteger" },
        "minProperties": { "$ref": "#/definitions/nonNegativeIntegerDefault0" },
        "required": { "$ref": "#/definitions/stringArray" },
        "additionalProperties": { "$ref": "#/definitions/schema" },
        "definitions": {
          "type": "object",
          "additionalProperties": { "$ref": "#/definitions/schema" },
          "default": {}
        },
        "properties": {
          "type": "object",
          "additionalProperties": { "$ref": "#/definitions/schema" },
          "default": {}
        },
        "patternProperties": {
          "type": "object",
          "additionalProperties": { "$ref": "#/definitions/schema" },
          "propertyNames": { "format": "regex" },
          "default": {}
        },
        "dependencies": {
          "type": "object",
          "additionalProperties": {
            "anyOf": [{ "$ref": "#/definitions/schema" }, { "$ref": "#/definitions/stringArray" }]
          }
        },
        "propertyNames": { "$ref": "#/definitions/schema" },
        "const": {},
        "enum": {
          "type": "array",
          "minItems": 1,
          "uniqueItems": true
        },
        "type": {
          "anyOf": [
            { "$ref": "#/definitions/simpleTypes" },
            {
              "type": "array",
              "items": { "$ref": "#/definitions/simpleTypes" },
              "minItems": 1,
              "uniqueItems": true
            }
          ]
        },
        "format": { "type": "string" },
        "allOf": { "$ref": "#/definitions/schemaArray" },
        "anyOf": { "$ref": "#/definitions/schemaArray" },
        "oneOf": { "$ref": "#/definitions/schemaArray" },
        "not": { "$ref": "#/definitions/schema" }
      }
    }
  },
  "default": {},
  "$ref": "#/definitions/schema"
}

=== FurtherBank/json-schemaeditor-antd/src/json-example/$schema.general.json
{
  "type": "object",
  "title": "一系列测试",
  "properties": {
    "enumValue": {
      "enum": [
        15,
        "一段文字",
        false,
        [1, 2, 3, 4, 5],
        null,
        {
          "stuff": 123,
          "str": "一段文字"
        }
      ]
    },
    "constValue": {
      "description": "这个变量的值应该是数字 123",
      "const": 123
    },
    "typeError": {
      "description": "这个变量的类型应该是string，现在是object",
      "type": "string"
    },
    "newNameTest": {
      "type": "object",
      "title": "变量创建-命名测试",
      "description": "模式中对 properties, patternProperties, additionalProperties 都有定义，在这里测试新创建的属性名能否正确对应到相应模式，以及重命名空间是否正确。",
      "properties": {
        "pro1": {
          "type": "integer",
          "default": 1
        },
        "pro2": {
          "type": "integer",
          "default": 2
        },
        "pro3": {
          "type": "integer",
          "default": 3
        },
        "pro4": {
          "type": "integer",
          "default": 4
        },
        "pro5": {
          "type": "integer",
          "default": 5
        },
        "pro6": {
          "type": "integer",
          "default": 6
        }
      },
      "required": ["pro1", "pro2"],
      "patternProperties": {
        "pattern[0-9]+": {
          "description": "这个属性改名应该满足表达式 pattern[0-9]+",
          "type": "number"
        }
      },
      "additionalProperties": {
        "type": "number",
        "description": "这是 additionalProperties，应当<50",
        "maximum": 50
      }
    },
    "mess": {
      "title": "混乱",
      "description": "这个属性的模式定义是混乱的，意在这种情况下看组件是否正常工作。",
      "type": ["object", "array", "string", "number", "integer"],
      "properties": {
        "num": {
          "type": "number"
        }
      },
      "additionalProperties": {
        "type": "number"
      },
      "required": ["num"],
      "items": {
        "type": "string",
        "format": "color"
      },
      "format": "color",
      "maxLength": 5,
      "minimum": 20,
      "multipleOf": 2
    },
    "formats": {
      "type": "object",
      "title": "格式测试",
      "properties": {
        "color": {
          "type": "string",
          "format": "color"
        },
        "date": {
          "type": "string",
          "format": "date"
        },
        "email": {
          "type": "string",
          "format": "email"
        },
        "ipv4": {
          "type": "string",
          "format": "ipv4"
        },
        "row": {
          "type": "string",
          "format": "row"
        },
        "multi": {
          "type": "string",
          "format": "multiline"
        }
      }
    },
    "oneOfLayers": {
      "type": "array",
      "items": {
        "title": "oneOf套娃",
        "oneOf": [
          {
            "title": "套娃",
            "oneOf": [
              {
                "type": "object",
                "title": "类型为对象",
                "properties": {
                  "type": {
                    "enum": ["object", "array"]
                  }
                },
                "required": ["type"]
              },
              {
                "type": "object",
                "title": "类型为其它",
                "properties": {
                  "type": {
                    "enum": ["string", "number", "boolean", "integer", "null"]
                  }
                },
                "required": ["type"]
              }
            ]
          },
          {
            "title": "number[]",
            "type": "array",
            "items": {
              "type": "number"
            }
          },
          {
            "title": "string[]",
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          {
            "title": "color",
            "type": "string",
            "format": "color"
          },
          {
            "title": "email",
            "type": "string",
            "format": "email"
          },
          {
            "title": "date",
            "type": "string",
            "format": "date"
          }
        ]
      }
    },
    "smellyAndLong": {
      "enum": [
        "该项目是一个使用antd写的基于json-schema的json编辑器。 目前还在高速开发迭代中……\n该项目具有简单、可靠等特点。",
        "123",
        5
      ],
      "title": "又臭又长",
      "description": "这是一个又臭又长的枚举字符串。"
    }
  },
  "required": ["enumValue", "constValue", "typeError", "newNameTest", "formats"]
}

=== FurtherBank/json-schemaeditor-antd/packages/cpu-json-editor/src/demos/integrate/$schema.alternative.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "title": "替代法则测试",
  "type": "string",
  "$ref": "#/definitions/a",
  "definitions": {
    "a": {
      "title": "#/definitions/a",
      "description": "#/definitions/a",
      "$ref": "#/definitions/multiline"
    },
    "multiline": {
      "format": "multiline"
    }
  }
}

=== FurtherBank/json-schemaeditor-antd/src/JsonSchemaEditor/demos/json-example/$schema.alternative.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "type": "string",
  "title": "alternative",
  "$ref": "#/definitions/a",
  "definitions": {
    "a": {
      "title": "#/definitions/a",
      "description": "#/definitions/a",
      "$ref": "#/definitions/multiline"
    },
    "multiline": {
      "format": "multiline"
    }
  }
}

=== FurtherBank/json-schemaeditor-antd/src/schema-example/test-newName.json
{
    "type": "object",
    "properties": {
        "pro1": {
            "type": "integer"
        },
        "pro2": {
            "type": "integer"
        },
        "pro3": {
            "type": "integer"
        },
        "pro4": {
            "type": "integer"
        },
        "pro5": {
            "type": "integer"
        },
        "pro6": {
            "type": "integer"
        }
    },
    "required": ["pro1", "pro2"],
    "patternProperties": {
        "pattern[0-9]+": {
            "description":"这个属性改名应该满足表达式 pattern[0-9]+",
            "type": "number"
        }
    },
    "additionalProperties": {
        "type":"number",
        "description": "这是 additionalProperties，应当<50",
        "maximum": 50
    }
}
